# Generated by Django 5.1.6 on 2025-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_star_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='death_date',
            field=models.DateField(blank=True, help_text='Оставьте пустым, если знаменитость жива', null=True, verbose_name='Дата смерти'),
        ),
    ]
